variable "nsx" {}
variable "vcenter" {}
variable "external_gw" {}
variable "avi" {}
variable "avi_password" {}
variable "avi_old_password" {}
variable "avi_username" {}
variable "nsx_password" {}
variable "vcenter_password" {}
variable "esxi" {}
